/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Events.EventsWorkerOrganization;
import Business.UserAccount.UserAccount;
import Business.Util.Leftovers.Leftovers;
import Business.Util.Request.RequestStatus;
import Business.Util.Validation.Validation;
import Business.WorkQueue.CollectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author siri chowdhary
 */
public class MainJFrame extends javax.swing.JFrame  {
    
    public EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    

    /**
     * Creates new form MainJFrame
     */
    
    
    public MainJFrame()  {
        
         initComponents();
         system = dB4OUtil.retrieveSystem();
         RequestStatus.initalizePickupRequestStatusMap();
         RequestStatus.initializeInvoiceStatusMap();
         RequestStatus.initializeShortageStatusListMap();
         Leftovers.initializeFood();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftPane = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        loginPanelLabel = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPane.setBackground(new java.awt.Color(204, 204, 204));

        userNameLabel.setText("User Name:");

        passwordLabel.setText("Password:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.setEnabled(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        loginPanelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginPanelLabel.setText("Login Panel");

        javax.swing.GroupLayout leftPaneLayout = new javax.swing.GroupLayout(leftPane);
        leftPane.setLayout(leftPaneLayout);
        leftPaneLayout.setHorizontalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPaneLayout.createSequentialGroup()
                        .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(userNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTextField)
                            .addComponent(passwordTextField)))
                    .addGroup(leftPaneLayout.createSequentialGroup()
                        .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftPaneLayout.createSequentialGroup()
                                .addComponent(loginButton)
                                .addGap(72, 72, 72)
                                .addComponent(logoutButton))
                            .addComponent(loginPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftPaneLayout.setVerticalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(loginPanelLabel)
                .addGap(42, 42, 42)
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(31, 31, 31)
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(logoutButton))
                .addGap(222, 222, 222))
        );

        splitPane.setLeftComponent(leftPane);

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 204));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String userName=null;
        
        if(Validation.validateStringInput(usernameTextField))  {
            
            userName=usernameTextField.getText();
            
        } 
        else 
        {
            return;
        }

        char[] passChar=passwordTextField.getPassword();
        
        if(passChar  ==  null)  {
            
            JOptionPane.showMessageDialog(null, "Input cannot be blank" , "Warning" ,JOptionPane.WARNING_MESSAGE);
            passwordTextField.setBackground(Color.GREEN);
            return;
        }

        UserAccount ua=new UserAccount();
        String password=ua.encodePassword(String.valueOf(passChar));
        Enterprise inEnterprise=null;
        Organization inOrganization=null;
        Network network=null;
        ua=system.getUserAccountDirectory().searchUser(userName, password);

        if(ua==null)   {
            
            for(Network n  :  system.getNetworkList())  {
                
                for(Enterprise e  :  n.getEnterpriseDirectory().getEnterpriseList())  {
                    
                    ua=e.getUserAccountDirectory().searchUser( userName,password);
                    
                    if(ua  ==  null)   {
                        
                        for(Organization o  :  e.getOrganizationDirectory().getOrganizationList())  {
                            
                            ua=o.getUserAccountDirectory().searchUser(userName, password);
                            
                            if(ua  !=  null)  {
                                
                                inEnterprise=e;
                                inOrganization=o;
                                network=n;
                                break;
                            }
                        }
                    } 
                    else
                    {
                        inEnterprise=e;
                        network=n;
                        break;
                    }
                    if(inOrganization  !=  null)   
                    {
                        break;
                    }
                }
                if(network  !=  null)   {
                    break;
                }
            }
        }

        if(ua==null)   {
            
            JOptionPane.showMessageDialog(null,"Invalid credentials");
            
            return;
            
        } 
        else
        {
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("WorkArea",ua.getRole().createWorkArea(userProcessContainer,ua,inOrganization,inEnterprise,system,network));
            layout.next(userProcessContainer);

        }
        
        loginButton.setEnabled(false);
        logoutButton.setEnabled(true);
        usernameTextField.setEnabled(false);
        passwordTextField.setEnabled(false);
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        
        logoutButton.setEnabled(false);
        loginButton.setEnabled(true);
        usernameTextField.setEnabled(true);
        passwordTextField.setEnabled(true);

        
        usernameTextField.setText("");
        passwordTextField.setText("");

        
        userProcessContainer.removeAll();
        
        JPanel blankJP = new JPanel();
        userProcessContainer.add("blank",blankJP);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        

        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new MainJFrame().setVisible(true);
                ;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftPane;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginPanelLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

   
}
