/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Transportation.TransportationWorker;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author thiag
 */

public class TransportationWorkerWorkAreaJPanel extends javax.swing.JPanel   {

    /**
     * Creates new form TransportationWorkerJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;
    

    public TransportationWorkerWorkAreaJPanel ( JPanel userProcessContainer ,  UserAccount account, Enterprise enterprise, Network network) {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.account  =  account;
        this.enterprise  =  enterprise;
        this.network  =  network;
        
        nameValueLabel.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameValueLabel = new javax.swing.JLabel();
        pickupRequestButton = new javax.swing.JButton();
        deliveryRequestButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Transportation Worker - Work Area");

        nameLabel.setText("Welcome:");

        pickupRequestButton.setText("Pickup Requests");
        pickupRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupRequestButtonActionPerformed(evt);
            }
        });

        deliveryRequestButton.setText("Delivery Requests");
        deliveryRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deliveryRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickupRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(headerLabel)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(pickupRequestButton)
                .addGap(18, 18, 18)
                .addComponent(deliveryRequestButton)
                .addGap(168, 168, 168))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryRequestButtonActionPerformed
        
        TransportationWorkerDeliveryJPanel transportationWorkerDeliveryJPanel  =  new TransportationWorkerDeliveryJPanel ( userProcessContainer , account, enterprise, network);
        userProcessContainer.add("TransportationWorkerDeliveryJPanel", transportationWorkerDeliveryJPanel);
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_deliveryRequestButtonActionPerformed

    private void pickupRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupRequestButtonActionPerformed

        
        TransportationWorkerPickUpJPanel transportationWorkerPickUpJPanel  =  new TransportationWorkerPickUpJPanel ( userProcessContainer , account);
        userProcessContainer.add("TransportationWorkerPickUpJPanel",transportationWorkerPickUpJPanel);
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_pickupRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliveryRequestButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValueLabel;
    private javax.swing.JButton pickupRequestButton;
    // End of variables declaration//GEN-END:variables
}
