/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Transportation.TransportationWorker;

import Business.UserAccount.UserAccount;
import Business.Util.Request.RequestStatus;
import Business.WorkQueue.CollectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thiag
 */

public class TransportationWorkerPickUpJPanel extends javax.swing.JPanel   {

    /**
     * Creates new form TransportationWorkerPickUpJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;

    public TransportationWorkerPickUpJPanel ( JPanel userProcessContainer , UserAccount account)   {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.account  =  account;
        
        populateTable();
        
    }

    private void populateTable()   {
        

        DefaultTableModel dtm  =  (DefaultTableModel)transportationWorkerTable.getModel();
        dtm.setRowCount(0);
        
        for( WorkRequest workRequest  :  account.getWorkQueue().getWorkRequestList())   
        {
            if( workRequest instanceof CollectionWorkRequest)   
            {
                CollectionWorkRequest cwr  =  (CollectionWorkRequest) workRequest;

                Object row[]  =  new Object[6];

                row[0]  =  cwr.getRequestDate();
                row[1]  =  cwr.getRaisedByEvents();
                row[2]  =  cwr.getRaisedBy().getUsername();
                row[3]  =  cwr.getTotalQuantity() +"pounds";
                row[4]  =  cwr.getDeliverToNGO();
                row[5]  =  cwr;

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        transportationWorkerTable = new javax.swing.JTable();
        pickupButton = new javax.swing.JButton();
        headerLabel = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        transportationWorkerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Pickup Location", "Pick up person", "Package Weight", "Drop Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(transportationWorkerTable);
        if (transportationWorkerTable.getColumnModel().getColumnCount() > 0) {
            transportationWorkerTable.getColumnModel().getColumn(0).setResizable(false);
            transportationWorkerTable.getColumnModel().getColumn(1).setResizable(false);
            transportationWorkerTable.getColumnModel().getColumn(2).setResizable(false);
            transportationWorkerTable.getColumnModel().getColumn(3).setResizable(false);
            transportationWorkerTable.getColumnModel().getColumn(4).setResizable(false);
            transportationWorkerTable.getColumnModel().getColumn(5).setResizable(false);
        }

        pickupButton.setText("Pickup");
        pickupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupButtonActionPerformed(evt);
            }
        });

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Transportation Worker - Pick up list");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pickupButton))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerLabel)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(pickupButton))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pickupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupButtonActionPerformed

        
        int selectedRow  =  transportationWorkerTable.getSelectedRow();
        
        if(selectedRow < 0)   
        {
            JOptionPane.showMessageDialog( null , "Please select a request item to pickup" , "Warning" , JOptionPane.WARNING_MESSAGE);
            return;
        } 
        else 
        {
            CollectionWorkRequest request  =  (CollectionWorkRequest) transportationWorkerTable.getValueAt(selectedRow, 5);
            
            if( request.getStatus().equals(RequestStatus.getPickupStatusMessage(3))) 
            {

                TransportationWorkerPickUpDetailsJPanel transportationWorkerPickUpDetailsJPanel  = new  TransportationWorkerPickUpDetailsJPanel ( userProcessContainer , account, request);
                userProcessContainer.add("TransportationWorkerPickUpDetailsJPanel", transportationWorkerPickUpDetailsJPanel);
                
                CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            } 
            else 
            {
                JOptionPane.showMessageDialog ( null, "Pick-up already completed" , "Warning" , JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
    }//GEN-LAST:event_pickupButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblName;
    private javax.swing.JButton pickupButton;
    private javax.swing.JTable transportationWorkerTable;
    // End of variables declaration//GEN-END:variables
}
