/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Transportation.TransportationWorker;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.Util.Request.RequestStatus;
import Business.WorkQueue.CollectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thiag
 */
public class TransportationWorkerDeliveryJPanel extends javax.swing.JPanel  {

    /**
     * Creates new form TransportationWorkerDeliveryJPanel
     */
      
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;
    

    public TransportationWorkerDeliveryJPanel ( JPanel userProcessContainer , UserAccount account , Enterprise enterprise , Network network)   {
        
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.account  =  account;
        this.enterprise  =  enterprise;
        this.network  =  network;
        
        populateTable();
        
    }

    private void populateTable()   {

        DefaultTableModel dtm  =  (DefaultTableModel) transportationWorkerTable.getModel();
        dtm.setRowCount(0);
        
        for( WorkRequest workRequest  :  account.getWorkQueue().getWorkRequestList())   
        {
            if( workRequest instanceof CollectionWorkRequest)   
            {
                CollectionWorkRequest cwr  =  (CollectionWorkRequest) workRequest;

                Object row[]  =  new Object[6];

                row[0]  =  cwr.getRequestDate();
                row[1]  =  cwr.getRaisedByEvents();
                row[2]  =  cwr.getRaisedBy().getUsername();
                row[3]  =  cwr.getTotalQuantity() +" pounds";
                row[4]  =  cwr.getDeliverToNGO();
                row[5]  =  cwr;

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        transportationWorkerTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        confirmDeliveryButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Transportation Worker - Delivery Queue");

        transportationWorkerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Pickup Location", "Pick up person", "Package Weight", "Drop Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(transportationWorkerTable);

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        confirmDeliveryButton.setText("Confirm Delivery");
        confirmDeliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeliveryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmDeliveryButton))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(headerLabel)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(confirmDeliveryButton))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmDeliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeliveryButtonActionPerformed
        
        int selectedRow  =  transportationWorkerTable.getSelectedRow();
        
        if(selectedRow < 0)   
        {
            JOptionPane.showMessageDialog(null,"Please select a request item to deliver","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        } 
        else 
        {
            CollectionWorkRequest request  =  (CollectionWorkRequest) transportationWorkerTable.getValueAt(selectedRow, 5);
            if(request.getStatus().equals(RequestStatus.getPickupStatusMessage(4)))   
            {

                TransportationWorkerDeliveryDetailsJPanel transportationWorkerDeliveryDetailsJPanel  =  new TransportationWorkerDeliveryDetailsJPanel ( userProcessContainer , account, enterprise, request, network);
                userProcessContainer.add("TransportationWorkerDeliveryDetailsJPanel", transportationWorkerDeliveryDetailsJPanel);
                
                CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            } 
            else 
            {
                JOptionPane.showMessageDialog( null , "Request not in the proper state for delivery" , "Warning" , JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_confirmDeliveryButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmDeliveryButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable transportationWorkerTable;
    // End of variables declaration//GEN-END:variables
}
