/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Transportation.TransportationManager;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.PaymentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author thiag
 */

public class TransportationManagerViewChartJPanel extends javax.swing.JPanel  {

    private JPanel userProcessContainer;
    private UserAccount account;

    /**
     * Creates new form TransportationManagerViewChartJPanel
     */
    
    public TransportationManagerViewChartJPanel ( JPanel userProcessContainer, UserAccount account)   {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.account  =  account;
        
        populateChart();
    }

    public void populateChart()   {

        DefaultPieDataset dataSet  =  new DefaultPieDataset();
        int paid  =  0, unpaid  =  0;
        double paidAmount  =  0, unpaidAmount  =  0;

        for(WorkRequest wr  :  account.getWorkQueue().getWorkRequestList())   
        {
            if(wr instanceof PaymentWorkRequest)   
            {
                PaymentWorkRequest pwr  =  (PaymentWorkRequest) wr;
                
                if(pwr.getCollectionWorkRequest().getInvoiceGenerated())   
                {
                    if(pwr.getCollectionWorkRequest().getPaid())   
                    {
                        paid++;
                        paidAmount  +=  pwr.getCollectionWorkRequest().getDeliveryCost();
                    } 
                    else 
                    {
                        unpaid++;
                        unpaidAmount  +=  pwr.getCollectionWorkRequest().getDeliveryCost();
                    }
                }
            }
        }

        dataSet.setValue("Paid", paid);
        dataSet.setValue("Unpaid", unpaid);

        JFreeChart chart  =  ChartFactory.createPieChart("Paid and Unpaid Invoices",dataSet, true, true, true);

        PiePlot plot  =  (PiePlot)chart.getPlot();

        ChartPanel chartPanel  =  new ChartPanel(chart);
        pnlChart.removeAll();
        pnlChart.add(chartPanel, BorderLayout.CENTER);
        pnlChart.validate();

        paidValueLabel.setText("$ " + paidAmount);
        unPaidValueLabel.setText("$ " + unpaidAmount);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChart = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        paidLabel = new javax.swing.JLabel();
        paidValueLabel = new javax.swing.JLabel();
        unPaidLabel = new javax.swing.JLabel();
        unPaidValueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        pnlChart.setBackground(new java.awt.Color(255, 255, 204));
        pnlChart.setLayout(new java.awt.BorderLayout());

        headerLabel.setBackground(new java.awt.Color(204, 204, 255));
        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Transporation Manager - View Invoice Payement Status");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        paidLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paidLabel.setText("Total Amount Received (Paid) :");

        paidValueLabel.setText("paid");

        unPaidLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        unPaidLabel.setText("Total Amount Pending (Un-Paid) :");

        unPaidValueLabel.setText("un-paid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlChart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(unPaidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paidValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unPaidValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(headerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unPaidLabel)
                    .addComponent(unPaidValueLabel))
                .addGap(8, 8, 8)
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel paidLabel;
    private javax.swing.JLabel paidValueLabel;
    private javax.swing.JPanel pnlChart;
    private javax.swing.JLabel unPaidLabel;
    private javax.swing.JLabel unPaidValueLabel;
    // End of variables declaration//GEN-END:variables
}
