/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Events.EventsWorker;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CollectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author alves
 */

public class EventsWorkerWorkAreaJPanel extends javax.swing.JPanel   {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;

    /**
     * Creates new form EventsWorkerWorkArea
     */
    
    public EventsWorkerWorkAreaJPanel ( JPanel userProcessContainer , UserAccount account , Enterprise enterprise , Network network) {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.account  =  account;
        this.enterprise  =  enterprise;
        this.network  =  network;

        populateLoginDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        wastageLabel = new javax.swing.JLabel();
        wastageValueLabel = new javax.swing.JLabel();
        raiseCollectionRequestButton = new javax.swing.JButton();
        viewRequestLogButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Events Worker Work Area");

        nameLabel.setText("Welcome, ");

        wastageLabel.setText("Total wastage avoided :");

        wastageValueLabel.setText("wastage_avoided");

        raiseCollectionRequestButton.setText("Raise Collection Request");
        raiseCollectionRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseCollectionRequestButtonActionPerformed(evt);
            }
        });

        viewRequestLogButton.setText("View Request Log");
        viewRequestLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestLogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewRequestLogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(raiseCollectionRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(wastageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(wastageValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(headerLabel)
                .addGap(47, 47, 47)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wastageLabel)
                    .addComponent(wastageValueLabel))
                .addGap(33, 33, 33)
                .addComponent(raiseCollectionRequestButton)
                .addGap(27, 27, 27)
                .addComponent(viewRequestLogButton)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void raiseCollectionRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseCollectionRequestButtonActionPerformed
        
        EventsWorkerRaiseRequestJPanel eventsWorkerRaiseRequestJPanel  =  new EventsWorkerRaiseRequestJPanel ( userProcessContainer , account, enterprise.getName(), network);
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        
        userProcessContainer.add("EventsWorkerRaiseRequestJPanel", eventsWorkerRaiseRequestJPanel);
        layout.next(userProcessContainer);

    }//GEN-LAST:event_raiseCollectionRequestButtonActionPerformed

    private void viewRequestLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestLogButtonActionPerformed
        
        EventsWorkerViewRequestLogJPanel eventsWorkerViewRequestLogJPanel  =  new EventsWorkerViewRequestLogJPanel ( userProcessContainer, account);
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        
        userProcessContainer.add("EventsWorkerViewRequestLogJPanel", eventsWorkerViewRequestLogJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewRequestLogButtonActionPerformed

    private void populateLoginDetails()   {
        
        double quantity  =  0;
        
        nameLabel.setText(nameLabel.getText() + " " + account.getEmployee().getName());
        
        for(WorkRequest wr  :  account.getWorkQueue().getWorkRequestList()) 
        {
            if(wr instanceof CollectionWorkRequest)   
            { 
                CollectionWorkRequest cwr  =  (CollectionWorkRequest) wr;
                quantity  +=  cwr.getTotalQuantity();
            }
        }
        
        wastageValueLabel.setText(quantity + " pounds");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton raiseCollectionRequestButton;
    private javax.swing.JButton viewRequestLogButton;
    private javax.swing.JLabel wastageLabel;
    private javax.swing.JLabel wastageValueLabel;
    // End of variables declaration//GEN-END:variables
}
