/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Events.EventsWorker;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.CollectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alves
 */


public class EventsWorkerViewRequestLogJPanel extends javax.swing.JPanel   {

    private JPanel userProcessContainer;
    private UserAccount account;

    /**
     * Creates new form EventsWorkerViewRequestLogJPanel
     */
    
    public EventsWorkerViewRequestLogJPanel ( JPanel userProcessContainer, UserAccount account)   {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.account  =  account;

        populateTable();
        
    }

    public void populateTable()  {
        
        DefaultTableModel dtm  =  (DefaultTableModel) logTable.getModel();
        dtm.setRowCount(0);

        for(WorkRequest wr  :  account.getWorkQueue().getWorkRequestList())   
        {
            CollectionWorkRequest cwr  =  (CollectionWorkRequest) wr;

            Object row[]  =  new Object[4];
            row[0]  =  cwr.getRequestDate();
            row[1]  =  cwr;
            row[2]  =  cwr.getTotalQuantity();
            row[3]  =  cwr.getDeliverToNGO()  ==  null ? "Undelivered"  :  cwr.getDeliverToNGO();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        viewRequestItemButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Events Worker Work Area - Request Log");

        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Raised Date", "Status", "Quantity (in pounds)", "Collected By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(logTable);
        if (logTable.getColumnModel().getColumnCount() > 0) {
            logTable.getColumnModel().getColumn(0).setResizable(false);
            logTable.getColumnModel().getColumn(1).setResizable(false);
            logTable.getColumnModel().getColumn(2).setResizable(false);
            logTable.getColumnModel().getColumn(3).setResizable(false);
        }

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        viewRequestItemButton.setText("View Request Item");
        viewRequestItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(448, 448, 448)
                                .addComponent(viewRequestItemButton))
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerLabel)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(viewRequestItemButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewRequestItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestItemButtonActionPerformed

        int selectedRow  =  logTable.getSelectedRow();
        
        if(selectedRow < 0)   {
            
            JOptionPane.showMessageDialog(null, "Please select a request item to view details" , "Information" ,JOptionPane.INFORMATION_MESSAGE);
        } 
        else 
        {
            CollectionWorkRequest cwr  =  (CollectionWorkRequest) logTable.getValueAt(selectedRow, 1);

            EventsWorkerViewLogItemJPanel eventsWorkerViewLogItemJPanel  =  new EventsWorkerViewLogItemJPanel( userProcessContainer , cwr);
            CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
            
            userProcessContainer.add("EventsWorkerViewLogItemJPanel", eventsWorkerViewLogItemJPanel);
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewRequestItemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable logTable;
    private javax.swing.JButton viewRequestItemButton;
    // End of variables declaration//GEN-END:variables
}
