/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Events.EventsAdmin;

import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Util.Validation.Validation;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alves
 */


public class EventsManageEmployeeJPanel extends javax.swing.JPanel   {
    
    private JPanel userProcessContainer;
 
    private OrganizationDirectory organizationDir;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    
    
    public EventsManageEmployeeJPanel (JPanel userProcessContainer,OrganizationDirectory organizationDir)   {
        
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        
        this.organizationDir = organizationDir;

        populateOrganizationComboBox();
        
        populateOrganizationEmpComboBox();
    
    }
    
    private void populateTable( Organization organization)  {
        
        DefaultTableModel model  =  (DefaultTableModel) organizationTable.getModel();

        model.setRowCount(0);

        for(Employee employee  :  organization.getEmployeeDirectory().getEmployeeList())   {
            
             Object[] row = new Object[2];
             row[0] = employee.getId();
             row[1] = employee.getName();
             model.addRow(row);
        }
    }
    

    public void populateOrganizationComboBox()  {
        
        ogranizationComboBox.removeAllItems();

        for(Organization organization  :  organizationDir.getOrganizationList())   {
            
            ogranizationComboBox.addItem(organization);
        }
    }

    public void populateOrganizationEmpComboBox()   {
        
        organizationCreateComboBox.removeAllItems();

        for(Organization organization  :  organizationDir.getOrganizationList())   {
            
            organizationCreateComboBox.addItem(organization);
            
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        organizationLabel = new javax.swing.JLabel();
        ogranizationComboBox = new javax.swing.JComboBox();
        jScrollPane = new javax.swing.JScrollPane();
        organizationTable = new javax.swing.JTable();
        jSeparator = new javax.swing.JSeparator();
        organizationCreateLabel = new javax.swing.JLabel();
        organizationCreateComboBox = new javax.swing.JComboBox();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        createEmployeeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Events Adminstrative Work Area - Manage Employee");

        organizationLabel.setText("Organization");

        ogranizationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogranizationComboBoxActionPerformed(evt);
            }
        });

        organizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(organizationTable);
        if (organizationTable.getColumnModel().getColumnCount() > 0) {
            organizationTable.getColumnModel().getColumn(0).setResizable(false);
            organizationTable.getColumnModel().getColumn(1).setResizable(false);
        }

        organizationCreateLabel.setText("Organization");

        organizationCreateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationCreateComboBoxActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        createEmployeeButton.setText("Create Employee");
        createEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(organizationLabel)
                                        .addGap(48, 48, 48)
                                        .addComponent(ogranizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(organizationCreateLabel)
                                    .addComponent(nameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(organizationCreateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(backButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createEmployeeButton)
                            .addGap(7, 7, 7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerLabel)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogranizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationCreateLabel)
                    .addComponent(organizationCreateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployeeButton)
                    .addComponent(backButton))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeButtonActionPerformed

        Organization organization  =  (Organization) organizationCreateComboBox.getSelectedItem();

        if(organization  ==  null)  {
            JOptionPane.showMessageDialog(null,"Invalid input");
            
            return;
        }

        String name  =  null;
        
        if(Validation.validateStringInput(nameTextField))   {
            
            name  =  nameTextField.getText();
        } 
        else 
        {
            return;
        }
        
        organization.getEmployeeDirectory().addEmployee(name);
        
        JOptionPane.showMessageDialog(null,  "Employee added successfully",  "Information",  JOptionPane.INFORMATION_MESSAGE);
        
        nameTextField.setText(" ");
        populateTable((Organization)ogranizationComboBox.getSelectedItem());
        

    }//GEN-LAST:event_createEmployeeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout   =  (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ogranizationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogranizationComboBoxActionPerformed
        Organization organization  =  (Organization)ogranizationComboBox.getSelectedItem();
        if(organization  !=  null)   
        {
            populateTable(organization);
        }
        
    }//GEN-LAST:event_ogranizationComboBoxActionPerformed

    private void organizationCreateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationCreateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationCreateComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createEmployeeButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox ogranizationComboBox;
    private javax.swing.JComboBox organizationCreateComboBox;
    private javax.swing.JLabel organizationCreateLabel;
    private javax.swing.JLabel organizationLabel;
    private javax.swing.JTable organizationTable;
    // End of variables declaration//GEN-END:variables
}
