package UserInterface.Events.EventsAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author alves
 */
public class EventsAdminWorkAreaJPanel extends javax.swing.JPanel   {

    
    
    private Enterprise enterprise;
    private EcoSystem business;
    private JPanel userProcessContainer;
    

    
    public EventsAdminWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem business)   {
        
        initComponents();
        this.enterprise = enterprise;
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        valueLabel.setText(enterprise.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageorganizationButton = new javax.swing.JButton();
        manageemployeeButton = new javax.swing.JButton();
        manageuserButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        headingLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headingLabel.setText("Events Adminstrative Work Area");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EVENTS");

        valueLabel.setText("<value>");

        manageorganizationButton.setText("Manage Organization");
        manageorganizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageorganizationButtonActionPerformed(evt);
            }
        });

        manageemployeeButton.setText("Manage Employee");
        manageemployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageemployeeButtonActionPerformed(evt);
            }
        });

        manageuserButton.setText("Manage User");
        manageuserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageuserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageorganizationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageemployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageuserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(headingLabel)))
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(headingLabel)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valueLabel)))
                .addGap(38, 38, 38)
                .addComponent(manageorganizationButton)
                .addGap(26, 26, 26)
                .addComponent(manageemployeeButton)
                .addGap(27, 27, 27)
                .addComponent(manageuserButton)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageuserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageuserButtonActionPerformed
        // TODO add your handling code here:
        
        
        EventsManageUserAccountJPanel muajp  =  new EventsManageUserAccountJPanel(userProcessContainer,enterprise,business);
        userProcessContainer.add("ManageUserAccountJPanel",muajp);
        

        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageuserButtonActionPerformed

    private void manageemployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageemployeeButtonActionPerformed

        EventsManageEmployeeJPanel eventsManageEmployeeJPanel  =  new EventsManageEmployeeJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
        userProcessContainer.add("eventsManageEmployeeJPanel",eventsManageEmployeeJPanel);
        

        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        

    }//GEN-LAST:event_manageemployeeButtonActionPerformed

    private void manageorganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageorganizationButtonActionPerformed

        EventsManageOrganizationJPanel eventsManageOrganizationJPanel  =  new EventsManageOrganizationJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
        userProcessContainer.add("eventsManageOrganizationJPanel",eventsManageOrganizationJPanel);
        
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageorganizationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton manageemployeeButton;
    private javax.swing.JButton manageorganizationButton;
    private javax.swing.JButton manageuserButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
