/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.systemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.Events.EventsAdminRole;
import Business.Role.Transportation.TransportationAdminRole;
import Business.Role.Role;
import Business.Role.NGO.NGOAdminRole;
import Business.UserAccount.UserAccount;
import Business.Util.Validation.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siri chowdhary
 */

public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel  {

    private JPanel userProcessContainer;
    private EcoSystem business;

    /**
     * Creates new form ManagerEnterpriseAdminJPanel
     */
    
    public ManageEnterpriseAdminJPanel ( JPanel userProcessContainer, EcoSystem business) {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.business  =  business;

        populateTable();
        populateNetworkComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        jSeparator = new javax.swing.JSeparator();
        networkLabel = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseComboBox = new javax.swing.JComboBox();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        addEnterpriseButton = new javax.swing.JButton();
        headerLabel = new javax.swing.JLabel();
        networkListLabel = new javax.swing.JLabel();
        createEnterpriseLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(enterpriseTable);

        networkLabel.setText("Network");

        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });

        enterpriseLabel.setText("Enterprise");

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        userNameLabel.setText("Username");

        passwordLabel.setText("Password");

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addEnterpriseButton.setText("ADD");
        addEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseButtonActionPerformed(evt);
            }
        });

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("System Admin Work Area - Create Enterprise Admin");

        networkListLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        networkListLabel.setText("Enterprise admin list:");

        createEnterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createEnterpriseLabel.setText("Create New Enterprise:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createEnterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(networkListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(443, 443, 443)
                                .addComponent(addEnterpriseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(networkLabel)
                                    .addComponent(enterpriseLabel))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(networkComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(userNameLabel)
                                    .addGap(52, 52, 52)
                                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordLabel)
                                        .addComponent(nameLabel))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(52, 52, 52)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(55, 55, 55)
                                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(headerLabel)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(networkListLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createEnterpriseLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkLabel)
                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel)
                    .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEnterpriseButton)
                    .addComponent(backButton))
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed

        Network network  =  (Network) networkComboBox.getSelectedItem();
        if(network  !=  null)  
        {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_networkComboBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        userProcessContainer.remove(this);
        
        Component[] componentArray  =  userProcessContainer.getComponents();
        
        Component component  =  componentArray[componentArray.length - 1];
        
        SystemAdminWorkAreaJPanel sysAdminwjp  =  (SystemAdminWorkAreaJPanel) component;
        
        sysAdminwjp.populateTree();
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void addEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseButtonActionPerformed

        Enterprise enterprise  =  (Enterprise) enterpriseComboBox.getSelectedItem();
        
        if(enterprise  ==  null)   
        {
                JOptionPane.showMessageDialog(null, "Invalid input!");
        }
            

        String userName  =  null;
        if(Validation.validateStringInput(userNameTextField))   
        {
            userName  =  userNameTextField.getText();
        } 
        else 
        {
            return;
        }

        String name  =  null;
        if(Validation.validateStringInput(nameTextField))   
        {
            userName  =  userNameTextField.getText();
        } 
        else 
        {
            return;
        }

        char[] passChar  =  passwordTextField.getPassword();
        if(passChar  ==  null || passChar.length  ==  0) 
        {
            JOptionPane.showMessageDialog(null,"Password cannot be blank","Warning",JOptionPane.WARNING_MESSAGE);
            passwordTextField.setBackground(Color.RED);
            return;
        }

        if(business.checkIfUserNameIsUnique(userName))   
        {
            JOptionPane.showMessageDialog(null, "User name already exists. Please select a different one.");
            return;
        }

        Employee employee  =  enterprise.getEmployeeDirectory().addEmployee(name);
        UserAccount account  =  new UserAccount();

        String password  =  account.encodePassword(String.valueOf(passChar));

        if(null  !=  enterprise.getEnterpriseType()) 
        {
            switch(enterprise.getEnterpriseType()) 
            {
                case Events:
                    account  =  enterprise.getUserAccountDirectory().addUserAccount(userName, password, employee, (Role) new EventsAdminRole());
                    break;
                
                case NGO:
                    account  =  enterprise.getUserAccountDirectory().addUserAccount(userName, password, employee, (Role) new NGOAdminRole());
                    break;
                
                case Transportation:
                    account  =  enterprise.getUserAccountDirectory().addUserAccount(userName, password, employee, (Role) new TransportationAdminRole());
                    break;
                
                default:
                    
                    break;
            }
        }

        JOptionPane.showMessageDialog(null, "Enterprise admin added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

        userNameTextField.setText("");
        nameTextField.setText("");
        passwordTextField.setText("");

        populateTable();

    }//GEN-LAST:event_addEnterpriseButtonActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

   
    
    private void populateNetworkComboBox()   
    {
        networkComboBox.removeAllItems();

        for(Network network  :  business.getNetworkList())   
        {
            networkComboBox.addItem(network);
        }
    }
    
    private void populateTable()  {
        
        DefaultTableModel dtm  =  (DefaultTableModel) enterpriseTable.getModel();
        dtm.setRowCount(0);
        
        for(Network network  :  business.getNetworkList())   
        {
            for(Enterprise enterprise  :  network.getEnterpriseDirectory().getEnterpriseList()) 
            {
                for(UserAccount userAccount  :  enterprise.getUserAccountDirectory().getUserAccountList())   
                {
                    Object[] row  =  new Object[3];
                    row[0]  =  enterprise.getName();
                    row[1]  =  network.getName();
                    row[2]  =  userAccount.getUsername();

                    dtm.addRow(row);
                }
            }
        }
    }


    private void populateEnterpriseComboBox ( Network network)   {
        
        enterpriseComboBox.removeAllItems();

        for(Enterprise enterprise  :  network.getEnterpriseDirectory().getEnterpriseList())   
        {
            enterpriseComboBox.addItem(enterprise);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel createEnterpriseLabel;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JLabel networkLabel;
    private javax.swing.JLabel networkListLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
