/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.systemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Util.Validation.Validation;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siri chowdhary
 */

public class ManageEnterpriseJPanel extends javax.swing.JPanel   {
    

    private JPanel userProcessContainer;
    private EcoSystem business;

    /**
     * Creates new form ManageEnterpriseJPanel
     */ 
    
    public ManageEnterpriseJPanel ( JPanel userProcessContainer , EcoSystem business)  {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.business  =  business;
        
        populateTable();
        populateComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        jSeparator = new javax.swing.JSeparator();
        networkLabel = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        enterpriseTypeLabel = new javax.swing.JLabel();
        enterpriseComboBox = new javax.swing.JComboBox();
        enterpriseNameLabel = new javax.swing.JLabel();
        enterprisenameTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        addEnterpriseButton = new javax.swing.JButton();
        headerLabel = new javax.swing.JLabel();
        networkListLabel = new javax.swing.JLabel();
        createEnterpriseLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(enterpriseTable);

        networkLabel.setText("Network");

        enterpriseTypeLabel.setText("Enterprise Type");

        enterpriseNameLabel.setText("Name");

        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addEnterpriseButton.setText("Add");
        addEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseButtonActionPerformed(evt);
            }
        });

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("System Admin Work Area - Create Enterprise");

        networkListLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        networkListLabel.setText("Enterprise list:");

        createEnterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createEnterpriseLabel.setText("Create New Enterprise:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(383, 383, 383)
                                .addComponent(addEnterpriseButton))
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(networkListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createEnterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(networkLabel)
                            .addComponent(enterpriseTypeLabel)
                            .addComponent(enterpriseNameLabel))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterprisenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(headerLabel)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(networkListLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createEnterpriseLabel)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkLabel)
                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseTypeLabel)
                    .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameLabel)
                    .addComponent(enterprisenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(addEnterpriseButton))
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        userProcessContainer.remove(this);
        
        Component[] componentArray  =  userProcessContainer.getComponents();
        
        Component component  =  componentArray[componentArray.length - 1];
        
        SystemAdminWorkAreaJPanel sysAdminwjp  =  (SystemAdminWorkAreaJPanel) component;
        
        sysAdminwjp.populateTree();

        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void addEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseButtonActionPerformed

        
        Network network  =  (Network) networkComboBox.getSelectedItem();
        EnterpriseType type  =  (Enterprise.EnterpriseType) enterpriseComboBox.getSelectedItem();

        if(network  ==  null || type  ==  null)   
        {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name  =  null;
        if(Validation.validateStringInput(enterprisenameTextField))   {
            
            name  =  enterprisenameTextField.getText();
        }
        else 
        {
            return;
        }

        boolean ifExists  =  network.getEnterpriseDirectory().checkIfEnterpriseExists ( name, type);

        if(ifExists) 
        {
            JOptionPane.showMessageDialog(null, "Enterprise name already exists");
            return;
        }

        network.getEnterpriseDirectory().addEnterprise ( name, type);
        JOptionPane.showMessageDialog(null, "Enterprise added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        enterprisenameTextField.setText("");
        populateTable();
        
    }//GEN-LAST:event_addEnterpriseButtonActionPerformed

    
    
     private void populateComboBox()   {
         
        networkComboBox.removeAllItems();
        enterpriseComboBox.removeAllItems();

        for(Network network  :  business.getNetworkList())   
        {
            networkComboBox.addItem(network);
        }

        for(Enterprise.EnterpriseType type  :  Enterprise.EnterpriseType.values())   
        {
            enterpriseComboBox.addItem(type);
        }

    }
     
     public void populateTable()   {
         
        DefaultTableModel dtm  =  (DefaultTableModel) enterpriseTable.getModel();
        dtm.setRowCount(0);
        
        for(Network n  :  business.getNetworkList())   
        {
            for(Enterprise e  :  n.getEnterpriseDirectory().getEnterpriseList()) 
            {
                Object row[]  =  new Object[3];
                row[0]  =  e;
                row[1]  =  n;
                row[2]  =  e.getEnterpriseType();
                dtm.addRow(row);
            }
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel createEnterpriseLabel;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JLabel enterpriseNameLabel;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JLabel enterpriseTypeLabel;
    private javax.swing.JTextField enterprisenameTextField;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JLabel networkLabel;
    private javax.swing.JLabel networkListLabel;
    // End of variables declaration//GEN-END:variables
}
