/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ngo.ngoWorker;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author siri chowdhary
 */
public class NGOWorkerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegionWorkerJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public NGOWorkerWorkAreaJPanel ( JPanel userProcessContainer , UserAccount account , Organization organization , Enterprise enterprise , EcoSystem business) {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.business  =  business;
        this.account  =  account;
        this.organization  =  organization;
        this.enterprise  =  enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        viewInventoryButton = new javax.swing.JButton();
        pickupDeliveryButton = new javax.swing.JButton();
        distributeFoodButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("NGO Worker WorkArea Panel");

        viewInventoryButton.setText("View Inventory");
        viewInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryButtonActionPerformed(evt);
            }
        });

        pickupDeliveryButton.setText("Pickup Delivery");
        pickupDeliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupDeliveryButtonActionPerformed(evt);
            }
        });

        distributeFoodButton.setText("Distribute Food");
        distributeFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributeFoodButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pickupDeliveryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(distributeFoodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(headerLabel)))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(headerLabel)
                .addGap(54, 54, 54)
                .addComponent(pickupDeliveryButton)
                .addGap(18, 18, 18)
                .addComponent(distributeFoodButton)
                .addGap(18, 18, 18)
                .addComponent(viewInventoryButton)
                .addGap(160, 160, 160))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryButtonActionPerformed
        // TODO add your handling code here:
        
        NGOWorkerViewInventoryJPanel nGOWorkerInventoryUpdateJPanel  =  new NGOWorkerViewInventoryJPanel ( userProcessContainer , enterprise);
        userProcessContainer.add("NGOWorkerInventoryUpdateJPanel", nGOWorkerInventoryUpdateJPanel);
        
        CardLayout layout  =  (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewInventoryButtonActionPerformed

    private void pickupDeliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupDeliveryButtonActionPerformed
        // TODO add your handling code here:
        
        NGOWorkerPickupDeliveryJPanel nGOWorkerInventoryUpdateJPanel  =  new NGOWorkerPickupDeliveryJPanel ( userProcessContainer , account , enterprise);
        userProcessContainer.add("NGOWorkerUpdateInventoryJPanel", nGOWorkerInventoryUpdateJPanel);
        
        CardLayout layout  =  (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_pickupDeliveryButtonActionPerformed

    private void distributeFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributeFoodButtonActionPerformed
        // TODO add your handling code here:
        
        NGOWorkerDistributeFoodJPanel distributeFoodJPanel  =  new NGOWorkerDistributeFoodJPanel ( userProcessContainer , enterprise);
        userProcessContainer.add("DistributeFoodJPanel", distributeFoodJPanel);
        
        CardLayout layout  =  (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_distributeFoodButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton distributeFoodButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton pickupDeliveryButton;
    private javax.swing.JButton viewInventoryButton;
    // End of variables declaration//GEN-END:variables
}
