/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Events.EventsManager;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role.RoleType;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CollectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author alves
 */
public class EventsManagerWorkAreaJPanel extends javax.swing.JPanel  {
    

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;

    /**
     * Creates new form EventsManagerWorkAreaJPanel
     */
    
    public EventsManagerWorkAreaJPanel ( JPanel userProcessContainer,  UserAccount account,  Enterprise enterprise)   {
        
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;

        populateLoginDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        wastageValueLabel = new javax.swing.JLabel();
        wastageLabel = new javax.swing.JLabel();
        requestLogButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Events Manager Work Area");

        nameLabel.setText("Welcome, ");

        wastageValueLabel.setText("wastage_avoided");

        wastageLabel.setText("Total wastage avoided :");

        requestLogButton.setText("View Request Log");
        requestLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestLogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(requestLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(wastageLabel)
                                    .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wastageValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerLabel)
                .addGap(48, 48, 48)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wastageLabel)
                    .addComponent(wastageValueLabel))
                .addGap(51, 51, 51)
                .addComponent(requestLogButton)
                .addGap(166, 166, 166))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateLoginDetails() 
    {
        double quantity  =  0;
        
        nameLabel.setText(nameLabel.getText() + " " + account.getEmployee().getName());
        
        for(Organization o  :  enterprise.getOrganizationDirectory().getOrganizationList()) 
        {
            for(UserAccount ua  :  o.getUserAccountDirectory().getUserAccountList()) 
            {
                if((ua.getRole().getRoleType().getValue()).equals(RoleType.EventsWorker.getValue()))   
                {
                    for(WorkRequest wr  :  ua.getWorkQueue().getWorkRequestList()) 
                    {
                        CollectionWorkRequest cwr  =  (CollectionWorkRequest) wr;
                        quantity  +=  cwr.getTotalQuantity();
                    }
                }
            }
        }
        
        wastageValueLabel.setText(quantity + " pounds");
    }

    private void requestLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestLogButtonActionPerformed
        
        EventsManagerViewRequestLogJPanel eventsManagerViewRequestLogJPanel  =  new EventsManagerViewRequestLogJPanel(userProcessContainer, enterprise);
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        
        userProcessContainer.add("EventsWorkerViewRequestLogJPanel", eventsManagerViewRequestLogJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestLogButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton requestLogButton;
    private javax.swing.JLabel wastageLabel;
    private javax.swing.JLabel wastageValueLabel;
    // End of variables declaration//GEN-END:variables
}
