/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Events.EventsManager;

import Business.Util.Request.RequestItem;
import Business.WorkQueue.CollectionWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alves
 */
public class EventsManagerViewLogItemJPanel extends javax.swing.JPanel   {
    

    private JPanel userProcessContainer;
    private CollectionWorkRequest collectionWorkRequest;

    
    /**
     * Creates new form EventsWorkerViewLogItemJPanel
     */
    
    public EventsManagerViewLogItemJPanel(JPanel userProcessContainer,CollectionWorkRequest collectionWorkRequest)   {
        
        initComponents();
        this.userProcessContainer  =  userProcessContainer;
        this.collectionWorkRequest  =  collectionWorkRequest;
        populateItemTable();
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        foodItemsTable = new javax.swing.JTable();
        requestFromLabel = new javax.swing.JLabel();
        requestFromValueLabel = new javax.swing.JLabel();
        requestDateLabel = new javax.swing.JLabel();
        requestDateValueLabel = new javax.swing.JLabel();
        requestStatusLabel = new javax.swing.JLabel();
        requestStatusValueLabel = new javax.swing.JLabel();
        leftoversQuantity = new javax.swing.JLabel();
        leftoversQuantityLabel = new javax.swing.JLabel();
        ngoLabel = new javax.swing.JLabel();
        ngoDeliveredToLabel = new javax.swing.JLabel();
        transportationLabel = new javax.swing.JLabel();
        transportationValueLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        chargesLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("Events Worker Work Area - Collection Request");

        foodItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Type", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(foodItemsTable);
        if (foodItemsTable.getColumnModel().getColumnCount() > 0) {
            foodItemsTable.getColumnModel().getColumn(0).setResizable(false);
            foodItemsTable.getColumnModel().getColumn(1).setResizable(false);
        }

        requestFromLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        requestFromLabel.setText("Raised by:");

        requestFromValueLabel.setText("request_from");

        requestDateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        requestDateLabel.setText("Request Date:");

        requestDateValueLabel.setText("request_date");

        requestStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        requestStatusLabel.setText("Request status:");

        requestStatusValueLabel.setText("request_status");

        leftoversQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        leftoversQuantity.setText("Leftovers Quantity:");

        leftoversQuantityLabel.setText("quantity");

        ngoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ngoLabel.setText("NGO delivered to:");

        ngoDeliveredToLabel.setText("ngo");

        transportationLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        transportationLabel.setText("Transportation");

        transportationValueLabel.setText("Transportation");

        costLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        costLabel.setText("Delivery Charges:");

        chargesLabel.setText("charges");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costLabel)
                            .addComponent(transportationLabel))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transportationValueLabel)
                            .addComponent(chargesLabel)))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftoversQuantity)
                            .addComponent(requestFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestStatusLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(requestDateValueLabel)
                                    .addComponent(requestStatusValueLabel)
                                    .addComponent(requestFromValueLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ngoDeliveredToLabel)
                                    .addComponent(leftoversQuantityLabel)))))
                    .addComponent(requestDateLabel))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerLabel)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestFromLabel)
                    .addComponent(requestFromValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDateLabel)
                    .addComponent(requestDateValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestStatusLabel)
                    .addComponent(requestStatusValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftoversQuantity)
                    .addComponent(leftoversQuantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngoLabel)
                    .addComponent(ngoDeliveredToLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportationLabel)
                    .addComponent(transportationValueLabel))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(chargesLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed

     public void populateData()  {

        requestFromValueLabel.setText(collectionWorkRequest.getRaisedBy().getEmployee().getName());
        
        requestDateValueLabel.setText(collectionWorkRequest.getRequestDate() + "");
        
        requestStatusValueLabel.setText(collectionWorkRequest.getStatus());
        
        leftoversQuantityLabel.setText(collectionWorkRequest.getTotalQuantity() + " pounds");

        String ngo  =  collectionWorkRequest.getDeliverToNGO()  ==  null ? "Undelivered"  :  collectionWorkRequest.getDeliverToNGO();
        ngoDeliveredToLabel.setText(ngo);

        String transportation  =  collectionWorkRequest.getDeliveredByTransportation() ==  null ? "Undelivered"  :  collectionWorkRequest.getDeliveredByTransportation();
        transportationValueLabel.setText(transportation);

        String cost  =  collectionWorkRequest.getDeliveryCost()  ==  0d ? "Undelivered"  :  "$" + collectionWorkRequest.getDeliveryCost();
        chargesLabel.setText(cost);

    }
    
    public void populateItemTable()   
    {
        DefaultTableModel dtm  =  (DefaultTableModel) foodItemsTable.getModel();
        dtm.setRowCount(0);

        for(RequestItem ri  :  collectionWorkRequest.getRequestItems())   
        {
            
            Object row[]  =  new Object[2];
            row[0]  =  ri;
            row[1]  =  ri.getQuantity();

            dtm.addRow(row);
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel chargesLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTable foodItemsTable;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel leftoversQuantity;
    private javax.swing.JLabel leftoversQuantityLabel;
    private javax.swing.JLabel ngoDeliveredToLabel;
    private javax.swing.JLabel ngoLabel;
    private javax.swing.JLabel requestDateLabel;
    private javax.swing.JLabel requestDateValueLabel;
    private javax.swing.JLabel requestFromLabel;
    private javax.swing.JLabel requestFromValueLabel;
    private javax.swing.JLabel requestStatusLabel;
    private javax.swing.JLabel requestStatusValueLabel;
    private javax.swing.JLabel transportationLabel;
    private javax.swing.JLabel transportationValueLabel;
    // End of variables declaration//GEN-END:variables
}
