/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ngo.ngoManager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.NGO.NGOManagerOrganization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.Util.Request.RequestStatus;
import Business.WorkQueue.ShortageWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author siri chowdhary
 */
public class NGOManagerRaiseShortageRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegionRequestJPanel
     */
    private JPanel userProcessContainer;
    private NGOEnterprise enterprise;
    private UserAccount account;
    private Network network;
    private boolean hasShortage = false;
    

    public NGOManagerRaiseShortageRequestJPanel ( JPanel userProcessContainer , UserAccount account , NGOEnterprise enterprise, Network network) {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.enterprise  =  enterprise;
        this.account  =  account;
        this.network  =  network;
        
        populateEmployeeDropDown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        selectEmployeeLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        employeeComboBox = new javax.swing.JComboBox();
        raiseRequestButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("NGO Manager - Shortage Request");

        selectEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectEmployeeLabel.setText("<HTML>Select <br/>Employee:</HTML>");

        messageLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        messageLabel.setText("Message:");

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane.setViewportView(messageTextArea);

        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        raiseRequestButton.setText("Raise Request");
        raiseRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(142, 142, 142)
                                .addComponent(raiseRequestButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(employeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(headerLabel)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(headerLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(raiseRequestButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void populateEmployeeDropDown()   
    {
        for( Organization organization  :  enterprise.getOrganizationDirectory().getOrganizationList())   
        {
            for( UserAccount user  :  organization.getUserAccountDirectory().getUserAccountList())  
            {
                if( user.getRole().getRoleType().getValue().equals(Role.RoleType.NGOWorker.getValue()))   
                {
                    employeeComboBox.addItem(user);
                }
            }
        }
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void raiseRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseRequestButtonActionPerformed
        // TODO add your handling code here:
        
        if( messageTextArea.getText()  ==  ""  ||  messageTextArea.getText()  ==  null) 
        {
            JOptionPane.showMessageDialog(null, "Please enter a message");
            return;
        }
        if( employeeComboBox.getSelectedItem()  ==  null)  
        {
            JOptionPane.showMessageDialog(null, "Please select an employee to assign the request to");
            return;
        }
        for( WorkRequest wr  :  account.getWorkQueue().getWorkRequestList()) 
        {
            if( wr instanceof ShortageWorkRequest) 
            {
                ShortageWorkRequest sr  =  (ShortageWorkRequest) wr;
                
                if( sr.getStatus().equals(RequestStatus.getShortageStatusMessage(1))) 
                {
                    hasShortage  =  true;
                    break;
                }
            }
        }
        if( hasShortage  ==  false) 
        {
            ShortageWorkRequest swr  =  new ShortageWorkRequest();
            
            swr.setSender(account);
            
            swr.setMessage(messageTextArea.getText());
            
            swr.setStatus(RequestStatus.getShortageStatusMessage(1));
            
            swr.setNgoName(enterprise.getName());
            
            swr.setAssignToEmployee((UserAccount) employeeComboBox.getSelectedItem());

            for( Enterprise e  :  network.getEnterpriseDirectory().getEnterpriseList())   
            {
                if( !e.getName().equals(enterprise.getName()))
                {
                    for( Organization o  :  e.getOrganizationDirectory().getOrganizationList()) 
                    {
                        if( o instanceof NGOManagerOrganization)   
                        {
                            o.getWorkQueue().getWorkRequestList().add(swr);
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog ( null, "Shortage request sucessfully raised");
            account.getWorkQueue().getWorkRequestList().add(swr);
            messageTextArea.setText("");

        } 
        else 
        {
            JOptionPane.showMessageDialog ( null , "Already sent a request");
            messageTextArea.setText("");
            return;
        }

    }//GEN-LAST:event_raiseRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox employeeComboBox;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JButton raiseRequestButton;
    private javax.swing.JLabel selectEmployeeLabel;
    // End of variables declaration//GEN-END:variables
}
