/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ngo.ngoManager;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author siri chowdhary
 */
public class NGOManagerWorkAreaJPanel extends javax.swing.JPanel  {

    /**
     * Creates new form RegionManagerWorkArea
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private Network network;

    public NGOManagerWorkAreaJPanel ( JPanel userProcessContainer , UserAccount account , Organization organization , Enterprise enterprise, Network network) {
        
        initComponents();
        
        this.userProcessContainer  =  userProcessContainer;
        this.account  =  account;
        this.organization  =  organization;
        this.enterprise  =  enterprise;
        this.network  =  network;
        
        nameLabel.setText(account.getEmployee().getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        managerNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        eventsRequestButton = new javax.swing.JButton();
        viewInventoryButton = new javax.swing.JButton();
        payInvoicesButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerLabel.setText("NGO Manager Work Area");

        managerNameLabel.setText("Manager Name: ");

        nameLabel.setText("View Name");

        eventsRequestButton.setText("Events Requests");
        eventsRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsRequestButtonActionPerformed(evt);
            }
        });

        viewInventoryButton.setText("View Inventory");
        viewInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryButtonActionPerformed(evt);
            }
        });

        payInvoicesButton.setText("Pay Invoices");
        payInvoicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payInvoicesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(managerNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eventsRequestButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(payInvoicesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(headerLabel)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerNameLabel)
                    .addComponent(nameLabel))
                .addGap(41, 41, 41)
                .addComponent(eventsRequestButton)
                .addGap(18, 18, 18)
                .addComponent(viewInventoryButton)
                .addGap(18, 18, 18)
                .addComponent(payInvoicesButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eventsRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsRequestButtonActionPerformed
        // TODO add your handling code here:
        
        NGOEventsRequestJPanel eventsRequestJPanel  =  new NGOEventsRequestJPanel ( userProcessContainer, account, organization, enterprise, network);
        userProcessContainer.add("EventsRequestJPanel", eventsRequestJPanel);
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_eventsRequestButtonActionPerformed

    private void viewInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryButtonActionPerformed
        // TODO add your handling code here:
        
        NGOWorkerViewInventoryJPanel viewNGOInventoryJPanel  =  new NGOWorkerViewInventoryJPanel ( userProcessContainer, enterprise, account, network);
        userProcessContainer.add("ViewNGOInventoryJPanel", viewNGOInventoryJPanel);
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewInventoryButtonActionPerformed

    private void payInvoicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payInvoicesButtonActionPerformed
        // TODO add your handling code here:
        
        NGOManagerPayInvoiceJPanel ngoManagerPayInvoiceJPanel  =  new NGOManagerPayInvoiceJPanel ( userProcessContainer , account , organization);
        userProcessContainer.add("NGOManagerPayInvoiceJPanel", ngoManagerPayInvoiceJPanel);
        
        CardLayout layout  =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_payInvoicesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eventsRequestButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel managerNameLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton payInvoicesButton;
    private javax.swing.JButton viewInventoryButton;
    // End of variables declaration//GEN-END:variables
}
